### PR TITLE
single video page

### PR DESCRIPTION
**Pull request by nyyshaaa**
refactors from previous branches and single video page.

### CODE REVIEW

**Review by arpit01923 — APPROVED** [review]
- clean code
- good folder structure
- one suggestion, try absolute paths

**Review by mcmonojit — APPROVED** [review]
Code looks good to merge. There are a number of commented codes which can be removed. You have used **vw** and **vh** which creates issues sometimes so check your application to make sure it is performing as intended.

**Comment by nyyshaaa** [comment]
> Code looks good to merge. There are a number of commented codes which can be removed. You have used **vw** and **vh** which creates issues sometimes so check your application to make sure it is performing as intended.

okeiy will look into it ,also i will refactor css in end.Thank you for reviewing!

**Comment by nyyshaaa** [comment]
> * clean code
> * good folder structure
> * one suggestion, try absolute paths

Thank you for reviewing!

**Review by anshtripathi01 — APPROVED** [review]
UI and code looks clean go ahead.

**Comment by nyyshaaa** [comment]
> UI and code looks clean go ahead.

Thanks for review!

**Pull request merged**
